# Generated by Django 3.1 on 2020-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_sys', models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=100, verbose_name='设备系统')),
                ('device_version', models.CharField(max_length=100, verbose_name='系统版本')),
                ('device_brand', models.CharField(max_length=200, verbose_name='设备品牌')),
                ('device_owner', models.CharField(max_length=200, verbose_name='设备归属人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
