# Generated by Django 3.1 on 2020-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
