# Generated by Django 3.1 on 2020-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apistep',
            old_name='apitest_param',
            new_name='api_param',
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_response',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
    ]
