# Generated by Django 3.1 on 2020-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniautomationresult',
            name='build_result',
            field=models.CharField(choices=[('0', '构建中'), ('1', '成功'), ('2', '失败')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='miniautomationresult',
            name='job_url',
            field=models.URLField(default='', verbose_name='Job地址'),
        ),
        migrations.AlterField(
            model_name='miniautomationresult',
            name='report_file',
            field=models.FileField(default='', upload_to='report/mini/ui/'),
        ),
    ]
