# Generated by Django 3.1 on 2020-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20200908_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniautomationresult',
            name='job_url',
        ),
    ]
