# Generated by Django 3.1 on 2020-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_miniautomationresult_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniautomationresult',
            name='case_num',
            field=models.IntegerField(default=0, verbose_name='用例数量'),
        ),
        migrations.AddField(
            model_name='miniautomationresult',
            name='fail_num',
            field=models.IntegerField(default=0, verbose_name='失败用例数量'),
        ),
        migrations.AlterField(
            model_name='miniautomationresult',
            name='build_result',
            field=models.CharField(choices=[('1', '通过'), ('2', '失败')], max_length=1),
        ),
        migrations.AlterField(
            model_name='miniautomationresult',
            name='report_file',
            field=models.FileField(null=True, upload_to='report/mini/ui/'),
        ),
    ]
